authen/urls.py
from django.urls import path
from . import views

app_name = 'authen'

urlpatterns = [
    path('', views.landing_view, name='landing'),
    path('landing', views.landing_view, name='landing'),
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('dropdown/', views.dropdown_view, name='dropdown')
]

django_auth/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authen.urls')),
]

authen/models.py
from django.db import models

# Create your models here.

authen/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model


# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            # return render(request, 'authen/dashboard.html',{})
            return get_users_view(request)
    else:
        form = UserCreationForm()
    return render(request, 'authen/signup.html', {'form': form})


def landing_view(request):
    return render(request, 'authen/landing.html')


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            # return render(request, 'authen/dashboard.html',{})
            return get_users_view(request)
    else:
        form = AuthenticationForm()
    return render(request, 'authen/login.html', {'form': form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('/landing')


def get_users_view(request):
    all_users = get_user_model().objects.all()
    context = {'all_users': all_users}
    return render(request, 'authen/dashboard.html', context)


def dropdown_view(request):
    if request.method == 'POST':
        username = request.POST['item_id']
        print(username)
        u = get_user_model().objects.get(username=username)
        u.delete()
        return get_users_view(request)

authen/templates/authen/dashboard.html
{% extends "./layout/base1.html" %}
{% load static %}

{% block content %}
    <h1>Dashboard</h1>
    <b>Select a user to delete : </b>
    <form action="{% url 'authen:dropdown' %}" method="post">
        {% csrf_token %}
        <select name="item_id">
        {% for entry in all_users %}
            <option value="{{ entry }}">{{ entry }}</option>
        {% endfor %}
        </select>
        <input type="submit" value="Delete User">
    </form>
{% endblock content %}

authen/templates/authen/landing.html
{% extends "./layout/base.html" %}
{% load static %}

{% block content %}
    <h1>Registeration</h1>
    <a class="btn btn-primary" href="login"><button>Admin Login</button></a><br><br>
    <a class="btn btn-primary" href="signup"><button>Admin Signup</button> </a>
{% endblock content %}

authen/templates/authen/layout/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% load static %}
    <link rel="stylesheet" href="{% static "posts/css/bootstrap.min.css" %}">

    <title>Home</title>
</head>
<body class="container mt-5">

    {% block content %}

    {% endblock content %}
</body>
</html>

authen/templates/authen/layout/base1.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% load static %}
    <link rel="stylesheet" href="{% static "posts/css/bootstrap.min.css" %}">

    <title>Algoscale</title>
</head>
<body class="container mt-5">

    {% block content %}

    {% endblock content %}
</body>
</html><!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% load static %}
    <link rel="stylesheet" href="{% static "posts/css/bootstrap.min.css" %}">

    <title>Home</title>
</head>
<body class="container mt-5">

    {% block content %}

    {% endblock content %}
</body>
</html>

authen/templates/authen/login.html
{% extends "./layout/base.html" %}
{% load static %}

{% block content %}
    <h1>Log In</h1>
    <form action="{% url 'authen:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Log In">
    </form>
{% endblock content %}

authen/templates/authen/signup.html
{% extends "./layout/base.html" %}
{% load static %}

{% block content %}
    <h1>Signup</h1>
    <form action="/signup/" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Signup">
    </form>
{% endblock content %}